### ISSUE TITLE
Failed to activate the veda package

### ISSUE THREAD

**Issue by Albpablo** [fand/veda#114] opened 2018-12-10 22:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Unknown Windows version
**Thrown From**: [veda](https://github.com/fand/veda) package 2.10.2

### Stack Trace

Failed to activate the veda package

```
At Cannot find module 'atom-message-panel'

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.33.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:145974)
    at /packages/veda/lib/wrapper.js:8:30)
    at /packages/veda/lib/wrapper.js:112:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:145974)
    at /packages/veda/lib/index.js:3:19)
    at /packages/veda/lib/index.js:90:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:1:626990)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3039740)
    at Package.activateNow (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3027874)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:14:1717)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1190583)
    at Emitter.emit (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1192024)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:349490)
```

### Commands

```
     -0:20.3.0 veda:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-deepscan 1.4.9 
atom-live-grammar-reload 0.8.0 
atom-python-package 0.7.1 
atom-python-run 0.9.7 
autocomplete-glsl 0.2.3 
browse 1.10.8 
busy-signal 1.4.3 
grammar-tab-colors 0.2.8 
greyatom-hydrogen 1.9.0 
Hydrogen 2.7.0 
ide-java 0.8.3 
ide-python 1.1.0 
intentions 1.1.5 
language-glsl 2.0.4 
linter 2.2.0 
linter-glsl 2.1.4 
linter-ui-default 1.7.1 
local-storage 0.7.3 
microbit-python 0.1.6 
nbviewer 1.0.2 
open-in-developer-mode 0.3.0 
open-package 0.2.0 
package-developer-toolbar 0.11.1 
pretty-json 2.0.3 
python-runner 1.2.1 
satisfy-dependencies 0.4.2 
tool-bar 1.1.11 
veda 2.10.2 
```

**Comment by fand** [comment] 2019-01-23 03:12
Thx @Albpablo ,

It seems Atom failed to install VEDA's dependencies correctly.
Reinstalling VEDA will fix it.

I'm gonna close this issue because it seems not a bug.
If you see the error again, plz comment here😸

**Closed as completed by fand** 2019-01-23 03:12 UTC
